<?php
/**
 * DTC List0r - File Manager script - version 2.2.0 (Apr 12 2011)
 * Copyright (C) 2007-2012 crxproject
 * http://github.com/crxproject/
 *
 * This work is licensed under the Creative Commons License http://creativecommons.org/licenses/by-sa/3.0/
 * The software is made available free of charge, no express or implied warranties are made.
 * Use at your own risk.
 */
/**
  VERSION HISTORY:

  2.2.0 (Apr 12, 2011)
 * subfolder access through .htaccess file (no more sub index.php needed)
 * added filetype icons

  2.1.2 (Jan 23, 2010)
 * ready for PHP 5.3.x

  2.1.1 (Jun 05, 2009)
 * added link to parent directory.
 * minor modification in formatsize function.

  2.1.0 (Aug 01, 2008)
 * fixed error "Undefined index: action in list.php on line 93" etc.

  2.0.4 (May 07, 2008)
 * filetype sortmode removed. Doesn't work properly.
 * minor html edits.

  2.0.3 (Apr 19, 2008)
 * content of (former standalone) config.php integrated

  2.0.2 (Feb 26, 2008)
 * shows "Current folder" on top.

  2.0.1 (Feb 20, 2008)
 * minor fixes.

  2.0.0 (Feb 20, 2008)
 * autogenerated md5 checksum.
 * Filesize format in kB, MB, GB, ...
 * fixed link encoding problem.
 * code redesigned.
 * fixed sortmode funtion error if folder is empty.

  1.0.1 (Sep 03, 2007)
 * Sort files case insensitive.

  1.0.0 (Jul 19, 2007)
 * Initial release.

 */
// Compares PHP version against our requirement.
if (version_compare(PHP_VERSION, '5.2.0', '<')) {
    die('List0r requires PHP 5.2.0 or higher to run. You are currently running PHP ' . PHP_VERSION . '.');
}

// error_reporting(E_ALL ^ E_NOTICE);
error_reporting(E_ALL);

// Base Configurations
$url = 'http://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']) . '/';
$baseDirname = join(array_slice(explode('/', $_SERVER['PHP_SELF']), 0, -1), '/') . '/';

define('SCRIPT_NAME', 'List0r - File Manager');
define('SCRIPT_VERSION', 'DTC List0r 2.2.0');
define('SCRIPT_HOME', 'http://github.com/crxproject/');

/*
 * Functions
 */

/**
 * Returns the size of a file (given in byte) as a String with kB/MB unit
 *
 * @param type $file_size
 * @return type
 */
function formatsize($file_size, $decimals = 2)
{

    $sizes = array('b', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB');
    $rext = $sizes[0];
    for ($i = 1; (($i < count($sizes)) && ($file_size >= 1024)); $i++) {
        $file_size = $file_size / 1024;
        $rext = $sizes[$i];
    }
    return round($file_size, $decimals) . '&#160;' . $rext;
}

/**
 * Files and folders not to display.
 *
 * @param type $name
 * @return boolean
 */
function isHidden($name)
{

    $name_arr = array('icons', 'index.php', '.htaccess', '.htpasswd', '.ftpquota');

    if (in_array($name, $name_arr)) {
        return true;
    } else {
        return false;
    }
}

/**
 *
 * @param type $dir
 * @param type $type
 * @return boolean
 */
function dirCounter($dir, $type)
{

    $file_count = 0;
    $dir_count = 0;

    $dh = opendir($dir);
    if ($dh) {
        $i = 0;

        while ($value = readdir($dh)) {
            $path = $dir . '/' . $value;

            if (is_dir($path) && $value != '.' && $value != '..' && !isHidden($value)) {
                $dir_count++;
            } elseif (is_file($path) && !isHidden($value)) {
                $file_count++;
            }
            $i++;
        }
        closedir($dh);
    } else {
        return false;
    }
    return $type == 'file' ? $file_count : $dir_count;
}

/**
 *
 */
function htaccess()
{

    if (!file_exists(dirname(__FILE__) . '/.htaccess')) {
        $rules = "<IfModule mod_rewrite.c>\n";
        $rules .= "Options +FollowSymlinks\n";
        $rules .= "RewriteEngine on\n";
        $rules .= "RewriteRule ^(.+)/$ index.php?dir=$1 [QSA,B]\n";
        $rules .= "</IfModule>";

        file_put_contents(dirname(__FILE__) . '/.htaccess', $rules);
    }
}

/**
 * Alter table row
 *
 * @staticvar int $i
 * @param type $return1
 * @param type $return2
 * @return type
 */
function row($return1 = 'class="even"', $return2 = 'class="odd"')
{
    static $i = 0;

    $i++;

    if ($i % 2 == 0) {
        return $return1;
    } else {
        return $return2;
    }
}

/**
 *
 */
function css_style()
{

    $output = '<!--

html { height: 101%; margin-bottom: 1px; }
body { font-size: 75%; line-height: 1em; background:#f0f0f0; color: #555555; font-family: sans-serif, Arial, Verdana, Geneva, Helvetica; }
a { color: #006699; outline: none; text-decoration: none; }
a:hover { color: #006699; text-decoration: underline; }
img { border: none; vertical-align: middle; }
#pagewidth { margin: 0 auto; width: 960px; }
.container { padding: 1.25em 3em; background: #FFFFFF; }
#error { font-size:1em; position: relative; margin: 0.5em 0; padding: 0.8em; border: 2px solid #fbc2c4; text-align: center; background: #fbe3e4; color: #8a1f11; }
#content { padding: 0 0.25em; }
.this { width: 100%; padding: 1em 0; text-align: left; font-size: 1.2em; font-weight: bold; }
table { border-collapse: collapse; border-spacing: 0; font-weight: normal; font-size: 12px; width: 100%; text-align: left; margin-bottom: 1em; }
thead { border-bottom: 1px #999999 solid; font-size: 1.1em; font-weight: bold; }
th, td { padding: 0.4em 0.6em; }
th { text-align: left; text-transform: uppercase; }
th a, th a:hover { color: #555555; text-decoration: none; }
tbody tr.even:hover, tbody tr.odd:hover { background-color: #f9f9db; }
tr.even, tr.odd { color: #333333; }
tr.even { background-color: #ffffff; }
tr.odd { background-color: #f5f5f5; }
.left { text-align: left; }
.right { text-align: right; }
.icon { width: 16px; }
.entry{ width: 80%; }
.details { white-space: nowrap; }
tfoot { border-top: 1px #999999 solid; }
#footer { width: 100%; padding: 10px 0; }

//-->';

    echo $output;
}

/**
 * Filetypes
 *
 * @param type $ext
 * @param type $default
 * @return type
 */
function getFiletypes($ext, $default = '')
{

    $filetypes = array(
        '7z' => 'zip.png',
        'asc' => 'sig.png',
        'avi' => 'movie.png',
        'bmp' => 'img.png',
        'doc' => 'doc.png',
        'eps' => 'eps.png',
        'exe' => 'bin.png',
        'fh10' => 'fh10.png',
        'fla' => 'fla.png',
        'flv' => 'swf.png',
        'gif' => 'img.png',
        'gz' => 'zip.png',
        'htm' => 'npp.png',
        'html' => 'npp.png',
        'jpeg' => 'img.png',
        'jpg' => 'img.png',
        'mp3' => 'winamp.png',
        'mpeg' => 'movie.png',
        'mp4' => 'movie.png',
        'mpg' => 'movie.png',
        'mov' => 'mov.png',
        'pdf' => 'pdf.png',
        'php' => 'php.png',
        'png' => 'img.png',
        'psd' => 'psd.png',
        'rar' => 'rar.png',
        'rm' => 'real.png',
        'setup' => 'bin.png',
        'sig' => 'sig.png',
        'swf' => 'swf.png',
        'txt' => 'text.png',
        'wav' => 'winamp.png',
        'xls' => 'xls.png',
        'xml' => 'xml.png',
        'zip' => 'zip.png',
    );

    return !empty($filetypes[$ext]) ? $filetypes[$ext] : $default;
}

/**
 * Mimetypes
 *
 * @param type $ext
 * @param type $default
 * @return type
 */
function getMimetypes($ext, $default = '')
{

    $mime_types = array(
        '323 ' => 'text/h323',
        'acutc' => 'application/vnd.acucorp',
        'acx' => 'application/internet-property-stream',
        'ai' => 'application/postscript',
        'aif' => 'audio/x-aiff',
        'aifc' => 'audio/x-aiff',
        'aiff' => 'audio/x-aiff',
        'ami' => 'application/vnd.amiga.amu',
        'ani' => 'application/octet-stream',
        'asc' => 'application/pgp',
        'asf' => 'video/x-ms-asf',
        'asr' => 'video/x-ms-asf',
        'asx' => 'video/x-ms-asf',
        'atc' => 'application/vnd.acucorp',
        'au' => 'audio/basic',
        'avi' => 'video/x-msvideo',
        'axs' => 'application/olescript',
        'bak' => 'application/x-trash',
        'bas' => 'text/plain',
        'bat' => 'application/x-msdos-program',
        'bck' => 'application/VMSBACKUP',
        'bcpio' => 'application/x-bcpio',
        'bin' => 'application/octet-stream',
        'bleep' => 'application/bleeper',
        'bmp' => 'image/bmp',
        'book' => 'application/x-maker',
        'bpd' => 'application/vnd.hbci',
        'bz2' => 'application/x-bzip2',
        'c' => 'text/plain',
        'c++' => 'text/plain',
        'cat' => 'application/vnd.ms-pkiseccat',
        'cc' => 'text/plain',
        'ccc' => 'text/vnd.net2phone.commcenter.command',
        'cdf' => 'application/x-cdf',
        'cdy' => 'application/vnd.cinderella',
        'cer' => 'application/x-x509-ca-cert',
        'chrt' => 'application/vnd.kde.kchart',
        'cil' => 'application/vnd.ms-artgalry',
        'class' => 'application/octet-stream',
        'clp' => 'application/x-msclip',
        'cls' => 'text/x-tex',
        'cmx' => 'image/x-cmx',
        'cod' => 'image/cis-cod',
        'com' => 'application/x-msdos-program',
        'cpio' => 'application/x-cpio',
        'cpp' => 'text/x-c++src',
        'cpt' => 'application/mac-compactpro',
        'crd' => 'application/x-mscardfile',
        'crl' => 'application/pkix-crl',
        'crt' => 'application/x-x509-ca-cert',
        'cs' => 'text/plain',
        'csh' => 'application/x-csh',
        'csm' => 'application/cu-seeme',
        'css' => 'text/css',
        'csv' => 'text/csv',
        'cu' => 'application/cu-seeme',
        'curl' => 'application/vnd.curl',
        'cw' => 'application/prs.cww',
        'cww' => 'application/prs.cww',
        'cxx' => 'text/x-c++src',
        'dcr' => 'application/x-director',
        'deb' => 'application/x-debian-package',
        'der' => 'application/x-x509-ca-cert',
        'dfac' => 'application/vnd.dreamfactory',
        'diff' => 'text/diff',
        'dir' => 'application/x-director',
        'dl' => 'video/dl',
        'dll' => 'application/x-msdownload',
        'dms' => 'application/octet-stream',
        'doc' => 'application/msword',
        'dot' => 'application/msword',
        'dvi' => 'application/x-dvi',
        'dxr' => 'application/x-director',
        'ecelp4800' => 'audio/vnd.nuera.ecelp4800',
        'ecelp7470' => 'audio/vnd.nuera.ecelp7470',
        'ecelp9600' => 'audio/vnd.nuera.ecelp9600',
        'emm' => 'application/vnd.ibm.electronic-media',
        'eol' => 'audio/vnd.digital-winds',
        'eps' => 'application/postscript',
        'etx' => 'text/x-setext',
        'evy' => 'application/envoy',
        'exe' => 'application/octet-stream',
        'ez' => 'application/andrew-inset',
        'fb' => 'application/x-maker',
        'fbdoc' => 'application/x-maker',
        'fif' => 'application/fractals',
        'fli' => 'video/fli',
        'flo' => 'application/vnd.micrografx.flo',
        'flr' => 'x-world/x-vrml',
        'flw' => 'application/vnd.kde.kivio',
        'fm' => 'application/x-maker',
        'frame' => 'application/x-maker',
        'frm' => 'application/x-maker',
        'fsc' => 'application/vnd.fsc.weblauch',
        'gf' => 'application/x-tex-gf',
        'gif' => 'image/gif',
        'gl' => 'video/gl',
        'gsf' => 'application/x-font',
        'gsm' => 'audio/x-gsm',
        'gtar' => 'application/x-gtar',
        'gz' => 'application/x-gzip',
        'h' => 'text/plain',
        'h++' => 'text/plain',
        'hbc' => 'application/vnd.hbci',
        'hbci' => 'application/vnd.hbci',
        'hdf' => 'application/x-hdf',
        'hh' => 'text/plain',
        'hlp' => 'application/winhlp',
        'hpgl' => 'application/vnd.hp-HPGL',
        'hpp' => 'text/plain',
        'hqx' => 'application/mac-binhex40',
        'hta' => 'application/hta',
        'htc' => 'text/x-component',
        'htke' => 'application/vnd.kenameapp',
        'htm' => 'text/html',
        'html' => 'text/html',
        'htt' => 'text/webviewhtml',
        'hxx' => 'text/plain',
        'ica' => 'application/x-ica',
        'ice' => 'x-conference/x-cooltalk',
        'ico' => 'image/x-icon',
        'ics' => 'text/calendar',
        'ief' => 'image/ief',
        'ifb' => 'text/calendar',
        'iges' => 'model/iges',
        'igs' => 'model/iges',
        'igx' => 'application/vnd.micrografx.igx',
        'iii' => 'application/x-iphone',
        'imagemap' => 'application/imagemap',
        'imap' => 'application/imagemap',
        'ins' => 'application/x-internet-signup',
        'irp' => 'application/vnd.irepository.package+xml',
        'isp' => 'application/x-internet-signup',
        'jad' => 'text/vnd.sun.j2me.app-descriptor',
        'jar' => 'application/x-jar',
        'java' => 'text/x-java-source',
        'jfif' => 'image/pipeg',
        'jisp' => 'application/vnd.jisp',
        'jpe' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'js' => 'application/x-javascript',
        'json' => 'application/json',
        'kar' => 'audio/midi',
        'karbon' => 'application/vnd.kde.karbon',
        'kfo' => 'application/vnd.kde.kformula',
        'kom' => 'application/vnd.hbci',
        'kon' => 'application/vnd.kde.kontour',
        'ksp' => 'application/vnd.kde.kspread',
        'kwd' => 'application/vnd.kde.kword',
        'kwt' => 'application/vnd.kde.kword',
        'latex' => 'application/x-latex',
        'lbd' => 'application/vnd.llamagraphics.life-balance.desktop',
        'les' => 'application/vnd.hhe.lesson-player',
        'lha' => 'application/octet-stream',
        'log' => 'text/plain',
        'lrm' => 'application/vnd.ms-lrm',
        'lsf' => 'video/x-la-asf',
        'lsx' => 'video/x-la-asf',
        'ltx' => 'text/x-tex',
        'lvp' => 'audio/vnd.lucent.voice',
        'lzh' => 'application/octet-stream',
        'm13' => 'application/x-msmediaview',
        'm14' => 'application/x-msmediaview',
        'm3u' => 'audio/x-mpegurl',
        'maker' => 'application/x-maker',
        'man' => 'application/x-troff-man',
        'mcd' => 'application/mathcad',
        'mda' => 'application/vnd.ms-access',
        'mdb' => 'application/x-msaccess',
        'mde' => 'application/vnd.ms-access',
        'mdf' => 'application/access',
        'me' => 'application/x-troff-me',
        'mesh' => 'model/mesh',
        'mht' => 'message/rfc822',
        'mhtml' => 'message/rfc822',
        'mid' => 'audio/mid',
        'midi' => 'audio/midi',
        'mif' => 'application/x-mif',
        'mml' => 'text/mathml',
        'mny' => 'application/x-msmoney',
        'moc' => 'text/x-moc',
        'mov' => 'video/quicktime',
        'movie' => 'video/x-sgi-movie',
        'mp2' => 'video/mpeg',
        'mp3' => 'audio/mpeg',
        'mpa' => 'video/mpeg',
        'mpc' => 'application/vnd.mophun.certificate',
        'mpe' => 'video/mpeg',
        'mpeg' => 'video/mpeg',
        'mp4' => 'video/mp4',
        'mpg4' => 'video/mp4',
        'mpega' => 'audio/mpeg',
        'mpg' => 'video/mpeg',
        'mpga' => 'audio/mpeg',
        'mpm' => 'application/vnd.blueice.multipass',
        'mpn' => 'application/vnd.mophun.application',
        'mpp' => 'application/vnd.ms-project',
        'mpv2' => 'video/mpeg',
        'ms' => 'application/x-troff-ms',
        'mseq' => 'application/vnd.mseq',
        'msh' => 'model/mesh',
        'mvb' => 'application/x-msmediaview',
        'mxu' => 'video/vnd.mpegurl',
        'nc' => 'application/x-netcdf',
        'nim' => 'video/vnd.nokia.interleaved-multimedia',
        'nws' => 'message/rfc822',
        'o' => 'application/x-object',
        'oda' => 'application/oda',
        'old' => 'application/x-trash',
        'oprc' => 'application/vnd.palm',
        'p' => 'text/x-pascal',
        'p10' => 'application/pkcs10',
        'p12' => 'application/x-pkcs12',
        'p7b' => 'application/x-pkcs7-certificates',
        'p7c' => 'application/x-pkcs7-mime',
        'p7m' => 'application/x-pkcs7-mime',
        'p7r' => 'application/x-pkcs7-certreqresp',
        'p7s' => 'application/x-pkcs7-signature',
        'pac' => 'application/x-ns-proxy-autoconfig',
        'pas' => 'text/x-pascal',
        'patch' => 'text/diff',
        'pbm' => 'image/x-portable-bitmap',
        'pcf' => 'application/x-font',
        'pcf.Z' => 'application/x-font',
        'pdb' => 'application/vnd.palm',
        'pdf' => 'application/pdf',
        'pfa' => 'application/x-font',
        'pfb' => 'application/x-font',
        'pfr' => 'application/font-tdpfr',
        'pfx' => 'application/x-pkcs12',
        'pgb' => 'image/vnd.glocalgraphics.pgb',
        'pgm' => 'image/x-portable-graymap',
        'pgn' => 'application/x-chess-pgn',
        'pgp' => 'application/pgp-signature',
        'php' => 'application/x-httpd-php',
        'php3' => 'application/x-httpd-php3',
        'php3p' => 'application/x-httpd-php3-preprocessed',
        'phps' => 'application/x-httpd-php3-source',
        'pht' => 'application/x-httpd-php',
        'phtml' => 'application/x-httpd-php',
        'pk' => 'application/x-tex-pk',
        'pkd' => 'application/vnd.hbci',
        'pko' => 'application/ynd.ms-pkipko',
        'pl' => 'application/x-perl',
        'plb' => 'application/vnd.3gpp.pic-bw-large',
        'plj' => 'audio/vnd.everad.plj',
        'plt' => 'application/vnd.hp-HPGL',
        'pm' => 'application/x-perl',
        'pm5' => 'application/pagemaker',
        'pma' => 'application/x-perfmon',
        'pmc' => 'application/x-perfmon',
        'pml' => 'application/x-perfmon',
        'pmr' => 'application/x-perfmon',
        'pmw' => 'application/x-perfmon',
        'png' => 'image/png',
        'pnm' => 'image/x-portable-anymap',
        'po' => 'text/plain',
        'pot' => 'application/vnd.ms-powerpoint',
        'pot,' => 'application/vnd.ms-powerpoint',
        'ppm' => 'image/x-portable-pixmap',
        'pps' => 'application/vnd.ms-powerpoint',
        'ppt' => 'application/vnd.ms-powerpoint',
        'pqa' => 'application/vnd.palm',
        'prc' => 'application/vnd.palm',
        'prf' => 'application/pics-rules',
        'ps' => 'application/postscript',
        'ps-z' => 'application/postscript',
        'psb' => 'application/vnd.3gpp.pic-bw-small',
        'pt5' => 'application/pagemaker',
        'pti' => 'application/vnd.pvi.ptid1',
        'ptid' => 'application/vnd.pvi.ptid1',
        'pub' => 'application/x-mspublisher',
        'pvb' => 'application/vnd.3gpp.pic-bw-var',
        'qt' => 'video/quicktime',
        'qtl' => 'application/quicktimeplayer',
        'qwd' => 'application/vnd.Quark.QuarkXPress',
        'qwt' => 'application/vnd.Quark.QuarkXPress',
        'qxb' => 'application/vnd.Quark.QuarkXPress',
        'qxd' => 'application/vnd.Quark.QuarkXPress',
        'qxl' => 'application/vnd.Quark.QuarkXPress',
        'qxt' => 'application/vnd.Quark.QuarkXPress',
        'ra' => 'audio/x-pn-realaudio',
        'ram' => 'audio/x-pn-realaudio',
        'rar' => 'application/x-rar-compressed',
        'ras' => 'image/x-cmu-raster',
        'rct' => 'application/prs.nprend',
        'rdz' => 'application/vnd.data-vision.rdz',
        'rgb' => 'image/x-rgb',
        'rm' => 'audio/x-pn-realaudio',
        'rmi' => 'audio/mid',
        'rnd' => 'application/prs.nprend',
        'roff' => 'application/x-troff',
        'rpm' => 'audio/x-pn-realaudio-plugin',
        'rss' => 'application/rss+xml',
        'rtf' => 'application/rtf',
        'rtx' => 'text/richtext',
        'sav' => 'application/x-spss',
        'sbs' => 'application/x-spss',
        'sc' => 'application/vnd.ibm.secure-container',
        'scd' => 'application/x-msschedule',
        'sct' => 'text/scriptlet',
        'setpay' => 'application/set-payment-initiation',
        'setreg' => 'application/set-registration-initiation',
        'sgm' => 'text/sgml',
        'sgml' => 'text/sgml',
        'sh' => 'application/x-sh',
        'shar' => 'application/x-shar',
        'shtml' => 'text/html',
        'sik' => 'application/x-trash',
        'silo' => 'model/mesh',
        'sit' => 'application/x-stuffit',
        'skd' => 'application/x-koan',
        'skm' => 'application/x-koan',
        'skp' => 'application/x-koan',
        'skt' => 'application/x-koan',
        'smi' => 'application/smil',
        'smil' => 'application/smil',
        'sms' => 'application/vnd.3gpp.sms',
        'snd' => 'audio/basic',
        'so' => 'application/octet-stream',
        'soc' => 'application/sgml-open-catalog',
        'spc' => 'application/x-pkcs7-certificates',
        'spl' => 'application/futuresplash',
        'spo' => 'application/x-spss',
        'spp' => 'application/x-spss',
        'sps' => 'application/x-spss',
        'src' => 'application/x-wais-source',
        'sst' => 'application/vnd.ms-pkicertstore',
        'stc' => 'application/vnd.sun.xml.calc.template',
        'std' => 'application/vnd.sun.xml.draw.template',
        'sti' => 'application/vnd.sun.xml.impress.template',
        'stk' => 'application/hyperstudio',
        'stl' => 'application/vnd.ms-pkistl',
        'stm' => 'text/html',
        'stw' => 'application/vnd.sun.xml.writer.template',
        'sty' => 'text/x-tex',
        'sv4cpio' => 'application/x-sv4cpio',
        'sv4crc' => 'application/x-sv4crc',
        'swf' => 'application/x-shockwave-flash',
        'swfl' => 'application/x-shockwave-flash',
        'sxc' => 'application/vnd.sun.xml.calc',
        'sxd' => 'application/vnd.sun.xml.draw',
        'sxg' => 'application/vnd.sun.xml.writer.global',
        'sxi' => 'application/vnd.sun.xml.impress',
        'sxm' => 'application/vnd.sun.xml.math',
        'sxw' => 'application/vnd.sun.xml.writer',
        't' => 'application/x-troff',
        'tar' => 'application/x-tar',
        'tbk' => 'application/toolbook',
        'tbz' => 'application/x-gtar',
        'tbz2' => 'application/x-gtar',
        'tcl' => 'application/x-tcl',
        'tex' => 'application/x-tex',
        'texi' => 'application/x-texinfo',
        'texinfo' => 'application/x-texinfo',
        'tgz' => 'application/x-compressed',
        'tif' => 'image/tiff',
        'tiff' => 'image/tiff',
        'tk' => 'text/x-tcl',
        'tr' => 'application/x-troff',
        'trm' => 'application/x-msterminal',
        'tsp' => 'application/dsptype',
        'tsv' => 'text/tab-separated-values',
        'txt' => 'text/plain',
        'uls' => 'text/iuls',
        'upa' => 'application/vnd.hbci',
        'ustar' => 'application/x-ustar',
        'vbk' => 'audio/vnd.nortel.vbk',
        'vbs' => 'text/plain',
        'vcd' => 'application/x-cdlink',
        'vcf' => 'text/x-vcard',
        'vcs' => 'text/calendar',
        'vfb' => 'text/calendar',
        'vis' => 'application/vnd.visionary',
        'vrm' => 'x-world/x-vrml',
        'vrml' => 'x-world/x-vrml',
        'vsc' => 'application/vnd.vidsoft.vidconference',
        'vsd' => 'application/vnd.visio',
        'wav' => 'audio/x-wav',
        'wax' => 'audio/x-ms-wax',
        'wbmp' => 'image/vnd.wap.wbmp',
        'wbxml' => 'application/vnd.wap.wbxml',
        'wcm' => 'application/vnd.ms-works',
        'wdb' => 'application/vnd.ms-works',
        'wk' => 'application/x-123',
        'wks' => 'application/vnd.ms-works',
        'wm' => 'video/x-ms-wm',
        'wma' => 'audio/x-ms-wma',
        'wmd' => 'application/x-ms-wmd',
        'wmf' => 'application/x-msmetafile',
        'wml' => 'text/vnd.wap.wml',
        'wmlc' => 'application/vnd.wap.wmlc',
        'wmls' => 'text/vnd.wap.wmlscript',
        'wmlsc' => 'application/vnd.wap.wmlscriptc',
        'wmv' => 'video/x-ms-wmv',
        'wmx' => 'video/x-ms-wmx',
        'wmz' => 'application/x-ms-wmz',
        'wp' => 'application/wordperfect',
        'wp5' => 'application/wordperfect5.1',
        'wp6' => 'application/wordperfect6.1',
        'wpd' => 'application/wordperfectd',
        'wpl' => 'application/vnd.ms-wpl',
        'wps' => 'application/vnd.ms-works',
        'wrd' => 'application/msword',
        'wri' => 'application/x-mswrite',
        'wrl' => 'x-world/x-vrml',
        'wrz' => 'x-world/x-vrml',
        'wvx' => 'video/x-ms-wvx',
        'wz' => 'application/x-Wingz',
        'x_b' => 'model/vnd.parasolid.transmit.binary',
        'x_t' => 'model/vnd.parasolid.transmit.text',
        'xaf' => 'x-world/x-vrml',
        'xbm' => 'image/x-xbitmap',
        'xfdf' => 'application/vnd.adobe.xfdf',
        'xht' => 'application/xhtml+xml',
        'xhtml' => 'application/xhtml+xml',
        'xla' => 'application/vnd.ms-excel',
        'xlc' => 'application/vnd.ms-excel',
        'xlm' => 'application/vnd.ms-excel',
        'xls' => 'application/vnd.ms-excel',
        'xlt' => 'application/vnd.ms-excel',
        'xlw' => 'application/vnd.ms-excel',
        'xml' => 'application/xml',
        'xmt_bin' => 'model/vnd.parasolid.transmit.binary',
        'xmt_txt' => 'model/vnd.parasolid.transmit.text',
        'xof' => 'x-world/x-vrml',
        'xpm' => 'image/x-xpixmap',
        'xsl' => 'text/xml',
        'xul' => 'application/vnd.mozilla.xul+xml',
        'xwd' => 'image/x-xwindowdump',
        'xyz' => 'chemical/x-xyz',
        'z' => 'application/x-compress',
        'zip' => 'application/zip'
    );

    return !empty($mime_types[$ext]) ? $mime_types[$ext] : $default;
}

/**
 *
 * @param type $time
 * @return type
 */
function getFiletime($time)
{

    return gmdate('Y/m/d - H:i', filemtime($time));
}

/**
 * Start timer
 *
 * @global type $starttime
 */
function timer_start()
{
    global $starttime;
    $mtime = microtime();
    $mtime = explode(' ', $mtime);
    $mtime = $mtime[1] + $mtime[0];
    $starttime = $mtime;
}

/**
 * Stop timer
 *
 * @global type $starttime
 * @return type
 */
function timer_stop()
{
    global $starttime;
    $mtime = microtime();
    $mtime = explode(' ', $mtime);
    $mtime = $mtime[1] + $mtime[0];
    $endtime = $mtime;
    $totaltime = round(($endtime - $starttime), 5);
    return $totaltime;
}

/**
 *
 * @global type $msg
 */
function error_message()
{
    global $msg;

    echo '<tr>
                        <td colspan="4" style="padding:0;"><div id="error">' . $msg . '</div></td>
                    </tr>';
}

/*
 * File Organizer
 */
$dir = !empty($_GET['dir']) ? $_GET['dir'] : '';
$by = !empty($_GET['by']) ? $_GET['by'] : '';
$order = !empty($_GET['order']) ? $_GET['order'] : '';

// if $dir is the current directory make $dir "." so opendir doesn't fail.
$dir = $dir == '' ? '.' : $dir . '/';

if (strpos($dir, '../') === false) {

    $total_files = 0;
    $total_folders = 0;
    $total_size = 0;

    $open_dir = @opendir($dir);
    if ($open_dir) {

        // if $dir is "." make it blank again so it doesn't screw up links in the main directory.
        if ($dir == '.') {
            $dir = '';
        }

        // Loop through directory files time!
        while (false !== ($file = readdir($open_dir))) {

            // drop this
            if ($file != '.' && $file != '..' && !isHidden($file)) {

                // it's a file
                if (is_file($dir . $file)) {

                    $size = filesize($dir . $file);
                    $time = filemtime($dir . $file);

                    if (isset($by) && $by == 'time') {
                        $files[$time . '-' . $file] = $file;
                    } elseif (isset($by) && $by == 'size') {
                        $files[$size . '-' . $file] = $file;
                    } else {
                        $files[] = $file;
                    }

                    $total_files++;
                    $total_size += $size;
                }

                // it's a folder
                elseif (is_dir($dir . $file)) {

                    $filesAmount = dirCounter($dir . $file, 'file');
                    $folderAmount = dirCounter($dir . $file, 'folder');

                    $size = ($folderAmount + $filesAmount);
                    $time = filemtime($dir . $file);

                    if (isset($by) && $by == 'time') {
                        $folders[$time . '-' . $file] = $file;
                    } elseif (isset($by) && $by == 'size') {
                        $folders[$size . '-' . $file] = $file;
                    } else {
                        $folders[] = $file;
                    }

                    $total_folders++;
                }
            }
        }

        @closedir($open_dir);
    } else {
        $msg = ('Unable to read directory.');
    }
}

//if(!isset($by)){$by == 'name';};
$order = !empty($order) ? $order : '';
$sort = '&#160;<img src="' . $url . 'icons/' . $order . '.png" alt="" />';

htaccess();
timer_start();
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta charset="utf-8" />
        <title><?php echo SCRIPT_NAME; ?></title>

        <style type="text/css"><?php css_style(); ?></style>

    </head>
    <body>

        <div id="pagewidth">
            <div class="container">

                <div class="this">
                    Current Directory:&#160;&#160;<?php echo $baseDirname . $dir; ?>
                </div>

                <table class="main">
                    <thead>
                        <tr>
                            <th></th>
                            <th><a href="<?php echo $url . $dir; ?>?by=name<?php if (isset($by) && $by == 'name' && $order == 'desc') echo "&order=asc"; else echo '&order=desc'; ?>">Name<?php echo (isset($by) && $by == 'name' ? $sort : ''); ?></a></th>
                            <th><a href="<?php echo $url . $dir; ?>?by=size<?php if (isset($by) && $by == 'size' && $order == 'asc') echo '&order=desc'; else echo '&order=asc'; ?>">Size<?php echo (isset($by) && $by == 'size' ? $sort : ''); ?></a></th>
                            <th><a href="<?php echo $url . $dir; ?>?by=time<?php if (isset($by) && $by == 'time' && $order == 'asc') echo '&order=desc'; else echo '&order=asc'; ?>">Date<?php echo (isset($by) && $by == 'time' ? $sort : ''); ?></a></th>
                        </tr>
                    </thead>

                    <tfoot>
                        <tr>
                            <td></td>
                            <td colspan="3"><strong>Directory contains <?php echo $total_folders; ?> Folder(s) and <?php echo $total_files; ?> File(s) with a total amount of <?php echo formatsize($total_size); ?></strong></td>
                        </tr>
                    </tfoot>

                    <tbody>
                        <?php if (!empty($dir)) { ?>
                            <tr <?php echo row(); ?>>
                                <td class="icon"><img src="<?php echo $url; ?>icons/back.png" width="16" height="16" alt="" /></td>
                                <td><a href="../">Parent Directory</a></td>
                                <td></td>
                                <td></td>
                            </tr>
                        <?php } ?>

                        <?php
                        // Display error message (if there is nothing else to display)
                        if (isset($msg)) {
                            error_message();
                        }

                        if (!empty($files)) {

                            // sort files
                            if (isset($by) && $by == 'name' && $order == 'desc') {
                                $files = array_reverse($files, TRUE);
                            } elseif (isset($by) && ($by == 'time' || $by == 'size') && $order == 'asc') {
                                ksort($files, SORT_NUMERIC);
                            } elseif (isset($by) && ($by == 'time' || $by == 'size') && $order == 'desc') {
                                krsort($files, SORT_NUMERIC);
                            } else {
                                natcasesort($files);
                            }

                            // file output
                            foreach ($files as $file) {

                                $file_info = pathinfo($file);
                                $icon = $file_info['extension'];
                                $size = filesize($dir . $file);
                                ?>

                                <tr <?php echo row(); ?>>
                                    <td class="icon"><img src="<?php echo $url; ?>icons/<?php echo getFiletypes($icon); ?>" width="16" height="16" alt="" /></td>
                                    <td class="entry"><a href="<?php echo $file; ?>"><?php echo htmlentities($file); ?></a><br />
                                        <small>MD5 Checksum:&#160;<?php echo md5_file($dir . $file); ?></small></td>
                                    <td class="details"><?php echo formatsize($size); ?></td>
                                    <td class="details date"><?php echo getFiletime($dir . $file); ?></td>
                                </tr>
                                <?php
                            }
                        }

                        if (!empty($folders)) {

                            // sort folders
                            if (isset($by) && $by == 'name' && $order == 'desc') {
                                $folders = array_reverse($folders, TRUE);
                            } elseif (isset($by) && ($by == 'time' || $by == 'size') && $order == 'asc') {
                                ksort($folders, SORT_NUMERIC);
                            } elseif (isset($by) && ($by == 'time' || $by == 'size') && $order == 'desc') {
                                krsort($folders, SORT_NUMERIC);
                            } else {
                                natcasesort($folders);
                            }

                            // folder output
                            foreach ($folders as $folder) {

                                $filesAmount = dirCounter($dir . $folder, 'file') . ' File(s)';
                                $folderAmount = dirCounter($dir . $folder, 'folder') . ' Folder(s)';

                                if ($folderAmount > 0 && $filesAmount > 0) {
                                    $folderSize = $folderAmount . ' and ' . $filesAmount;
                                } elseif ($folderAmount > 0) {
                                    $folderSize = $folderAmount;
                                } elseif ($filesAmount > 0) {
                                    $folderSize = $filesAmount;
                                } else {
                                    $folderSize = 'empty!';
                                }
                                ?>

                                <tr <?php echo row(); ?>>
                                    <td class="icon"><img src="<?php echo $url; ?>icons/folder.png" width="16" height="16" alt="" /></td>
                                    <td class="entry"><a href="<?php echo $folder; ?>"><?php echo htmlentities($folder); ?></a></td>
                                    <td class="details"><?php echo $folderSize; ?></td>
                                    <td class="details date"><?php echo getFiletime($dir . $folder); ?></td>
                                </tr>

        <?php
    }
}
?>
                    </tbody>
                </table>

            </div>

            <div id="footer" style="text-align: center;">Powered by <b><a href="<?php echo SCRIPT_HOME; ?>" target="_blank"><?php echo SCRIPT_NAME; ?></a></b></div>

        </div>

        <!--
        Powered by DTC List0r - File Manager (version {info:version}) -- Page generated in <?php echo timer_stop(); ?> seconds.
        //-->

    </body>
</html>